name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # --- START DEBUGGING STEPS ---
      - name: Print current working directory
        run: pwd

      - name: List files in root directory
        run: ls -la

      - name: List contents of src/
        run: ls -la src/

      - name: List contents of src/assets/
        run: ls -la src/assets/

      - name: List contents of src/assets/css/ (CRITICAL CHECK)
        run: ls -la src/assets/css/
      # --- END DEBUGGING STEPS ---

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site' # The directory containing your built site files
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./_site
          publish_branch: gh-pages

